from __future__ import annotations

from pathlib import PurePosixPath
from typing import TYPE_CHECKING, List

if TYPE_CHECKING:
    from .parser_core import GenerationStats


def _guess_language(path: str) -> str:
    ext = PurePosixPath(path).suffix.lower()
    mapping = {
        ".py": "python", ".js": "javascript", ".ts": "typescript",
        ".tsx": "tsx", ".jsx": "jsx", ".java": "java", ".c": "c",
        ".cpp": "cpp", ".go": "go", ".rs": "rust", ".rb": "ruby",
        ".sh": "bash", ".bash": "bash", ".json": "json", ".yaml": "yaml",
        ".yml": "yaml", ".toml": "toml", ".xml": "xml", ".html": "html",
        ".css": "css", ".sql": "sql", ".md": "markdown",
    }
    return mapping.get(ext, "")


def _format_stats(stats: GenerationStats) -> str:
    lines: List[str] = [f"- **Total files:** {stats.total_files}"]
    if stats.total_tokens is not None:
        lines.append(f"- **Approximate tokens:** {stats.total_tokens}")
    if stats.secrets_found:
        lines.append(f"- **Potential secrets flagged:** {stats.secrets_found}")
    return "\n".join(lines)


def build_markdown(
    *,
    processed_files: list[dict],
    directory_tree: str,
    stats: GenerationStats,
    repository_name: str,
    include_git_logs: bool,
    git_log_commits: list[dict],
) -> str:
    parts: List[str] = []

    parts.append(f"# {repository_name}\n\n")
    parts.append("Packed representation of the repository, generated by CodeParser.\n\n")
    parts.append(_format_stats(stats))
    parts.append("\n\n")

    parts.append("## Directory Structure\n\n")
    parts.append(f"```\n{directory_tree}\n```\n\n")

    parts.append("## Files\n\n")
    for file_info in sorted(processed_files, key=lambda f: f["path"]):
        path = file_info["path"]
        content = file_info["content"]
        lang = _guess_language(path)
        parts.append(f"### `{path}`\n\n")
        parts.append(f"```{lang}\n{content}\n```\n\n")

    if include_git_logs and git_log_commits:
        parts.append("## Git History\n\n")
        for commit in git_log_commits:
            date = commit.get("date", "")
            message = commit.get("message", "")
            files = commit.get("files", [])
            parts.append(f"- **{date}** -- {message}\n")
            for f in files:
                parts.append(f"  - `{f}`\n")
        parts.append("\n")

    return "".join(parts)
