from __future__ import annotations

from typing import TYPE_CHECKING, List

if TYPE_CHECKING:
    from .parser_core import GenerationStats

_SEPARATOR = "=" * 72


def build_text(
    *,
    processed_files: list[dict],
    directory_tree: str,
    stats: GenerationStats,
    repository_name: str,
    include_git_logs: bool,
    git_log_commits: list[dict],
) -> str:
    parts: List[str] = []

    parts.append(f"Repository: {repository_name}")
    parts.append("Generated by CodeParser")
    parts.append(f"Total files: {stats.total_files}")
    if stats.total_tokens is not None:
        parts.append(f"Approximate tokens: {stats.total_tokens}")
    if stats.secrets_found:
        parts.append(f"Potential secrets flagged: {stats.secrets_found}")
    parts.append("")

    parts.append(_SEPARATOR)
    parts.append("DIRECTORY STRUCTURE")
    parts.append(_SEPARATOR)
    parts.append(directory_tree)
    parts.append("")

    parts.append(_SEPARATOR)
    parts.append("FILES")
    parts.append(_SEPARATOR)
    parts.append("")

    for file_info in sorted(processed_files, key=lambda f: f["path"]):
        path = file_info["path"]
        content = file_info["content"]
        parts.append(f"--- {path} ---")
        parts.append(content)
        parts.append("")

    if include_git_logs and git_log_commits:
        parts.append(_SEPARATOR)
        parts.append("GIT HISTORY")
        parts.append(_SEPARATOR)
        for commit in git_log_commits:
            date = commit.get("date", "")
            message = commit.get("message", "")
            parts.append(f"  {date}  {message}")
            for f in commit.get("files", []):
                parts.append(f"    {f}")
        parts.append("")

    return "\n".join(parts)
