from __future__ import annotations

from typing import List

from .parser_core import GenerationStats


def _format_notes(stats: GenerationStats) -> str:
    lines: List[str] = [f"Total files included: {stats.total_files}"]
    if stats.total_tokens is not None:
        lines.append(f"Approximate total tokens: {stats.total_tokens}")
    if stats.secrets_found:
        lines.append(
            f"Potential secrets flagged by detect-secrets: {stats.secrets_found}",
        )
    return "\n".join(lines)


def build_repomix_xml(
    *,
    processed_files: list[dict],
    directory_tree: str,
    stats: GenerationStats,
    include_git_logs: bool,
    git_log_commits: list[dict],
) -> str:
    """Build a Repomix-style XML document.

    The structure mirrors Repomix's `xmlStyle.ts` template so that tools
    expecting Repomix output can consume CodeParser output directly.
    """

    notes = _format_notes(stats)

    parts: List[str] = []

    # <file_summary>
    parts.append(
        "<file_summary>\n"
        "This section contains a summary of this file.\n\n"
        "<purpose>\n"
        "This XML was generated by CodeParser. It packs your repository into a single, "
        "LLM-friendly artifact that is compatible with tools expecting Repomix XML.\n"
        "</purpose>\n\n"
        "<file_format>\n"
        "1. A <file_summary> section describing the purpose, structure, and statistics.\n"
        "2. A <directory_structure> section showing an indented tree of included paths.\n"
        "3. A <files> section containing the contents of each included file.\n"
        "4. An optional <git_logs> section with recent commit metadata when enabled.\n"
        "5. Multiple <file> entries, each with a path attribute and file contents.\n"
        "</file_format>\n\n"
        "<usage_guidelines>\n"
        "You can paste this XML into an LLM, or upload it as a file, to give the model "
        "a holistic view of your codebase. Use system prompts to explain how the model "
        "should interpret the <directory_structure> and <files> sections.\n"
        "</usage_guidelines>\n\n"
        "<notes>\n"
        f"{notes}\n"
        "</notes>\n\n"
        "</file_summary>\n\n",
    )

    # <directory_structure>
    parts.append("<directory_structure>\n")
    parts.append(directory_tree)
    parts.append("\n</directory_structure>\n\n")

    # <files>
    parts.append("<files>\n")
    parts.append("This section contains the contents of the repository's files.\n\n")

    for file_info in sorted(processed_files, key=lambda f: f["path"]):
        path = file_info["path"]
        content = file_info["content"]
        parts.append(f"<file path=\"{path}\">\n")
        parts.append(content)
        parts.append("\n</file>\n\n")

    parts.append("</files>\n")

    # Optional git logs
    if include_git_logs and git_log_commits:
        parts.append("<git_logs>\n")
        for commit in git_log_commits:
            parts.append("<git_log_commit>\n")
            parts.append(f"<date>{commit.get('date', '')}</date>\n")
            parts.append(f"<message>{commit.get('message', '')}</message>\n")
            parts.append("<files>\n")
            for f in commit.get("files", []):
                parts.append(f"{f}\n")
            parts.append("</files>\n")
            parts.append("</git_log_commit>\n")
        parts.append("</git_logs>\n")

    return "".join(parts)
